const API="/api/saas";
const state={csrf:"",orgId:"",period:null,history:[]};
const $=(id)=>document.getElementById(id);
const escapeHtml=(value)=>String(value??"").replace(/[&<>'"]/g,(ch)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));
const currentKstMonth=()=>new Date(Date.now()+9*60*60*1000).toISOString().slice(0,7);
function message(text,kind="ok"){const el=$("close-message");el.textContent=text;el.className=`message ${kind==="error"?"error":""}`;el.hidden=false;clearTimeout(message.timer);message.timer=setTimeout(()=>el.hidden=true,4200);}
async function api(path,{method="GET",body}={}){const headers={};if(body!==undefined)headers["content-type"]="application/json";if(state.csrf&&!['GET','HEAD'].includes(method))headers["x-csrf-token"]=state.csrf;const response=await fetch(`${API}${path}`,{method,headers,credentials:"same-origin",body:body===undefined?undefined:JSON.stringify(body)});let data=null;try{data=await response.json();}catch{}if(!response.ok){const error=new Error(data?.error||`http_${response.status}`);error.status=response.status;throw error;}return data;}
function formatTime(value){if(!value)return"-";return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}
function unresolvedHtml(snapshot){const risks=(snapshot?.risks?.items||[]).slice(0,5).map(item=>`<div class="unresolved-item"><strong>${escapeHtml(item.title)}</strong><span>Risk · ${escapeHtml(item.severity)} · ${escapeHtml(item.applicability)}</span></div>`);const actions=(snapshot?.actions?.items||[]).slice(0,5).map(item=>`<div class="unresolved-item"><strong>${escapeHtml(item.title)}</strong><span>Action · ${escapeHtml(item.status)}${item.dueDate?` · ${escapeHtml(item.dueDate)}`:""}${item.timingStatus==="OVERDUE"?" · 기한 지연":""}</span></div>`);return [...risks,...actions].slice(0,8).join("")||`<div class="unresolved-item"><strong>미해결 항목 없음</strong><span>현재 Snapshot 기준</span></div>`;}
function render(){const p=state.period;if(!p)return;const s=p.snapshot||{};const r=p.readiness||{};$("close-period-title").textContent=`${p.periodMonth} 점검`;$("close-status").textContent=p.status;$("close-status").classList.toggle("closed",p.status==="CLOSED");$("close-risk-count").textContent=s.risks?.activeTotal||0;$("close-action-count").textContent=s.actions?.active||0;$("close-overdue-count").textContent=s.actions?.overdue||0;$("close-completed-count").textContent=s.actions?.completedInPeriod||0;$("close-employee-count").textContent=s.organization?.employeeCount||0;$("close-workplace-count").textContent=s.organization?.workplaceCount||0;$("close-scope-count").textContent=s.organization?.complianceScopeCount||0;$("close-legal-version").textContent=s.legalContext?.legalRegistryVersion||"-";$("close-hash").textContent=p.snapshotHash?`${p.snapshotHash.slice(0,12)}…`:"-";$("close-unresolved").innerHTML=unresolvedHtml(s);
  const readiness=$("close-readiness");readiness.classList.toggle("alert",!!r.requiresAcknowledgement);readiness.innerHTML=r.requiresAcknowledgement?`<strong>미해결 ${r.unresolvedCount||0}건을 확인해야 마감할 수 있습니다.</strong>${r.requiresNote?"<br>Critical·High·기한 지연 항목이 있어 마감 메모도 필요합니다.":""}`:`<strong>현재 Snapshot에 미해결 Risk·Action이 없습니다.</strong>`;
  $("close-ack-wrap").hidden=!r.requiresAcknowledgement;$("close-note").required=!!r.requiresNote;$("close-open-controls").hidden=p.status==="CLOSED";$("close-closed-summary").hidden=p.status!=="CLOSED";if(p.status==="CLOSED")$("close-closed-summary").innerHTML=`<div class="readiness"><strong>${escapeHtml(p.periodMonth)} 점검 마감 완료</strong><br>마감: ${escapeHtml(formatTime(p.closedAt))}${p.closeNote?`<br>메모: ${escapeHtml(p.closeNote)}`:""}<br><small>닫힌 Snapshot은 이후 원본 데이터가 바뀌어도 수정되지 않습니다.</small></div>`;
}
function renderHistory(){const el=$("close-history");el.innerHTML=state.history.length?state.history.map(p=>`<div class="history-item"><b>${escapeHtml(p.periodMonth)}</b><div><strong>마감 완료</strong><p>${escapeHtml(formatTime(p.closedAt))}${p.closeNote?` · ${escapeHtml(p.closeNote)}`:""}</p></div><span class="badge closed">CLOSED</span></div>`).join(""):`<div class="unresolved-item"><strong>아직 월간 마감 기록이 없습니다.</strong></div>`;}
async function loadPeriod(){if(!state.orgId)return;const month=$("close-month").value||currentKstMonth();const [current,history]=await Promise.all([api(`/organizations/${state.orgId}/compliance-close/current?month=${encodeURIComponent(month)}`),api(`/organizations/${state.orgId}/compliance-close/history`)]);state.period=current.period;state.history=history.periods||[];render();renderHistory();}
async function bootstrap(){$("close-month").value=currentKstMonth();try{const me=await api("/auth/me");state.csrf=me.csrf;}catch(error){if(error.status===404){$("close-disabled").hidden=false;return;}$("close-auth-required").hidden=false;return;}try{const data=await api("/organizations");const organizations=data.organizations||[];if(!organizations.length){$("close-auth-required").hidden=false;return;}const picker=$("close-org-picker");picker.innerHTML=organizations.map(item=>`<option value="${escapeHtml(item.organization.id)}">${escapeHtml(item.organization.displayName||item.organization.legalName||item.organization.id)}</option>`).join("");const saved=localStorage.getItem("insaya_business_org");state.orgId=organizations.some(item=>item.organization.id===saved)?saved:organizations[0].organization.id;picker.value=state.orgId;$("close-workspace").hidden=false;await loadPeriod();}catch(error){message(`월간 점검을 불러오지 못했습니다: ${error.message}`,"error");}}
$("close-org-picker").addEventListener("change",async(e)=>{state.orgId=e.target.value;localStorage.setItem("insaya_business_org",state.orgId);try{await loadPeriod();}catch(error){message(error.message,"error");}});
$("close-month").addEventListener("change",()=>loadPeriod().catch(error=>message(error.message,"error")));
$("close-refresh").addEventListener("click",async()=>{try{const month=$("close-month").value;const data=await api(`/organizations/${state.orgId}/compliance-close/${month}/refresh`,{method:"POST",body:{}});state.period=data.period;render();message("최신 Risk·Action 상태로 Snapshot을 새로고침했습니다.");}catch(error){message(error.message,"error");}});
$("close-form").addEventListener("submit",async(e)=>{e.preventDefault();try{const month=$("close-month").value;const data=await api(`/organizations/${state.orgId}/compliance-close/${month}/close`,{method:"POST",body:{acknowledgeUnresolved:$("close-ack").checked,note:$("close-note").value}});state.period=data.period;await loadPeriod();message(data.idempotent?"이미 마감된 월입니다.":"월간 노무점검을 마감했습니다.");}catch(error){const labels={compliance_close_acknowledgement_required:"미해결 Risk·Action 확인 체크가 필요합니다.",compliance_close_note_required:"고위험 또는 기한 지연 항목이 있어 마감 메모가 필요합니다."};message(labels[error.message]||error.message,"error");}});
$("close-history-refresh").addEventListener("click",()=>loadPeriod().then(()=>message("마감 기록을 새로고침했습니다.")).catch(error=>message(error.message,"error")));
bootstrap();