import { cases } from "./runtime-case-repo.js";
import { renderDoc } from "./docs.js";
import { DISMISSAL_CASE_TYPE, createInitialDismissalCase, getDismissalIntakeState, getDismissalQuestions, normalizeDismissalFacts } from "./dismissal-intake.js";
import { buildDismissalActions, getDismissalNextAction } from "./dismissal-actions.js";
import { getDismissalLegalContext } from "./dismissal-rules.js";
import { buildDismissalDocuments, buildDismissalProcedures } from "./dismissal-resources.js";
import { buildDismissalCaseReport } from "./dismissal-report.js";

function isObject(value){return !!value&&typeof value==="object"&&!Array.isArray(value);}
function mergeFacts(existingFacts={},patch={}){const safeExisting=isObject(existingFacts)?existingFacts:{};const safePatch=isObject(patch)?patch:{};const merged={...safeExisting,...safePatch};if("evidence" in safePatch)merged.evidence={...(isObject(safeExisting.evidence)?safeExisting.evidence:{}),...(isObject(safePatch.evidence)?safePatch.evidence:{})};return normalizeDismissalFacts(merged);}
function derive(facts){const legal=getDismissalLegalContext(facts);const documents=buildDismissalDocuments(facts,legal);const procedures=buildDismissalProcedures(facts,legal);const calculations=legal.noticeAllowance?[{id:"dismissal.notice_allowance",type:"dismissal_notice_allowance",...legal.noticeAllowance,sourceId:"source.lsa.article26"}]:[];return{legal,documents,procedures,calculations};}
function toCaseUpdate(existingCase,facts){const generated=createInitialDismissalCase(facts);const derived=derive(generated.facts);return{status:generated.status,event_date:generated.event_date,period_start:generated.period_start,period_end:generated.period_end,employment_start_date:generated.employment_start_date,employment_end_date:generated.employment_end_date,facts:generated.facts,missing_facts:generated.missing_facts,issues:generated.issues,evidence:generated.evidence,calculations:derived.calculations,legal_sources:derived.legal.sources,documents:derived.documents,actions:buildDismissalActions(generated.facts),meta:{...(isObject(existingCase?.meta)?existingCase.meta:{}),...generated.meta,legalReferenceDate:derived.legal.referenceDate,legalVerifiedAt:derived.legal.verifiedAt}};}
function buildResult(caseRecord){const intake=getDismissalIntakeState(caseRecord.facts);const{legal,documents,procedures}=derive(caseRecord.facts);const nextAction=(Array.isArray(caseRecord.actions)&&caseRecord.actions[0])||getDismissalNextAction(caseRecord.facts);return{case:caseRecord,intake,questions:getDismissalQuestions(caseRecord.facts,3),legal,documents,procedures,nextAction};}

export async function createDismissalCase(facts={}){const record=createInitialDismissalCase(facts);const derived=derive(record.facts);record.calculations=derived.calculations;record.legal_sources=derived.legal.sources;record.documents=derived.documents;record.actions=buildDismissalActions(record.facts);record.meta={...(isObject(record.meta)?record.meta:{}),legalReferenceDate:derived.legal.referenceDate,legalVerifiedAt:derived.legal.verifiedAt};return buildResult(await cases.insert(record,"api:dismissal-intake"));}
export async function getDismissalCase(id){const found=await cases.get(id);if(!found)return{error:"case_not_found"};if(found.case_type!==DISMISSAL_CASE_TYPE)return{error:"case_type_mismatch",case:found};return buildResult(found);}
export async function updateDismissalCase(id,factsPatch={}){const current=await cases.get(id);if(!current)return{error:"case_not_found"};if(current.case_type!==DISMISSAL_CASE_TYPE)return{error:"case_type_mismatch",case:current};const facts=mergeFacts(current.facts,factsPatch);const updated=await cases.update(id,toCaseUpdate(current,facts),"api:dismissal-intake");return updated?buildResult(updated):{error:"case_not_found"};}
export async function renderDismissalDocument(id,templateKey,extraValues={}){const result=await getDismissalCase(id);if(result?.error)return result;const spec=result.documents.find((item)=>item.templateKey===templateKey);if(!spec)return{error:"document_not_supported"};const values={...spec.prefill,...(isObject(extraValues)?extraValues:{})};const rendered=renderDoc(templateKey,values);return rendered?{templateKey,values,document:rendered,caseId:id}:{error:"document_not_found"};}
export async function getDismissalCaseReport(id){const result=await getDismissalCase(id);return result?.error?result:buildDismissalCaseReport(result);}
