import { cases } from "./runtime-case-repo.js";
import { renderDoc } from "./docs.js";
import { RETIREMENT_CASE_TYPE, createInitialRetirementCase, getRetirementIntakeState, normalizeRetirementFacts } from "./retirement-intake.js";
import { buildRetirementActions, getRetirementNextAction } from "./retirement-actions.js";
import { getRetirementLegalContext } from "./retirement-rules.js";
import { buildRetirementDocuments, buildRetirementProcedures } from "./retirement-resources.js";
import { buildRetirementCaseReport } from "./retirement-report.js";
function isObject(value){return !!value&&typeof value==="object"&&!Array.isArray(value);}
function mergeFacts(existingFacts={},patch={}){const safeExisting=isObject(existingFacts)?existingFacts:{};const safePatch=isObject(patch)?patch:{};const merged={...safeExisting,...safePatch};if("evidence" in safePatch)merged.evidence={...(isObject(safeExisting.evidence)?safeExisting.evidence:{}),...(isObject(safePatch.evidence)?safePatch.evidence:{})};return normalizeRetirementFacts(merged);}
function derive(facts){const legal=getRetirementLegalContext(facts);const documents=buildRetirementDocuments(facts,legal);const procedures=buildRetirementProcedures(facts,legal);const calculations=[legal.averageWage?{id:"retirement.average_wage",type:"average_wage",...legal.averageWage}:null,legal.money?{id:"retirement.benefit",type:"retirement_benefit",...legal.money}:null].filter(Boolean);return{legal,documents,procedures,calculations};}
function toCaseUpdate(existingCase,facts){const generated=createInitialRetirementCase(facts);const derived=derive(generated.facts);return{status:generated.status,event_date:generated.event_date,period_start:generated.period_start,period_end:generated.period_end,employment_start_date:generated.employment_start_date,employment_end_date:generated.employment_end_date,facts:generated.facts,missing_facts:generated.missing_facts,issues:generated.issues,evidence:generated.evidence,calculations:derived.calculations,legal_sources:derived.legal.sources,documents:derived.documents,actions:buildRetirementActions(generated.facts),meta:{...(isObject(existingCase?.meta)?existingCase.meta:{}),...generated.meta,legalReferenceDate:derived.legal.referenceDate,legalVerifiedAt:derived.legal.verifiedAt,retirementMoneyStatus:derived.legal.money?.status}};}
function buildResult(caseRecord){const intake=getRetirementIntakeState(caseRecord.facts);const{legal,documents,procedures}=derive(caseRecord.facts);const nextAction=(Array.isArray(caseRecord.actions)&&caseRecord.actions[0])||getRetirementNextAction(caseRecord.facts);return{case:caseRecord,intake,legal,documents,procedures,nextAction};}
export async function createRetirementCase(facts={}){const record=createInitialRetirementCase(facts);const derived=derive(record.facts);record.calculations=derived.calculations;record.legal_sources=derived.legal.sources;record.documents=derived.documents;record.actions=buildRetirementActions(record.facts);record.meta={...(isObject(record.meta)?record.meta:{}),legalReferenceDate:derived.legal.referenceDate,legalVerifiedAt:derived.legal.verifiedAt,retirementMoneyStatus:derived.legal.money?.status};return buildResult(await cases.insert(record,"api:retirement-intake"));}
export async function getRetirementCase(id){const found=await cases.get(id);if(!found)return{error:"case_not_found"};if(found.case_type!==RETIREMENT_CASE_TYPE)return{error:"case_type_mismatch",case:found};return buildResult(found);}
export async function updateRetirementCase(id,factsPatch={}){const current=await cases.get(id);if(!current)return{error:"case_not_found"};if(current.case_type!==RETIREMENT_CASE_TYPE)return{error:"case_type_mismatch",case:current};const facts=mergeFacts(current.facts,factsPatch);const updated=await cases.update(id,toCaseUpdate(current,facts),"api:retirement-intake");return updated?buildResult(updated):{error:"case_not_found"};}
export async function renderRetirementDocument(id,templateKey,extraValues={}){const result=await getRetirementCase(id);if(result?.error)return result;const spec=result.documents.find((item)=>item.templateKey===templateKey);if(!spec)return{error:"document_not_supported"};const values={...spec.prefill,...(isObject(extraValues)?extraValues:{})};const rendered=renderDoc(templateKey,values);return rendered?{templateKey,values,document:rendered,caseId:id}:{error:"document_not_found"};}
export async function getRetirementCaseReport(id){const result=await getRetirementCase(id);return result?.error?result:buildRetirementCaseReport(result);}
