import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const requiredFiles=[
"server.js","wage-intake.html","wage-intake-client.js","wage-workspace.js","wage-report-ui.js",
"dismissal-intake.html","dismissal-intake-client.js","dismissal-intake.css",
"retirement-intake.html","retirement-intake-client.js","retirement-intake.css",
"worktime-intake.html","worktime-intake-client.js","worktime-intake.css",
"annual-leave-intake.html","annual-leave-intake-client.js","annual-leave-intake.css",
"scripts/browser-e2e.mjs","scripts/annual-leave-browser-e2e.mjs","scripts/write-build-info.mjs","scripts/production-smoke.mjs","scripts/annual-leave-production-smoke.mjs","lib/case-routes.js",
"lib/wage-intake-service.js","lib/wage-money.js","lib/legal-rules.js","lib/wage-resources.js","lib/wage-report.js",
"lib/dismissal-intake.js","lib/dismissal-rules.js","lib/dismissal-actions.js","lib/dismissal-resources.js","lib/dismissal-report.js","lib/dismissal-service.js",
"lib/retirement-intake.js","lib/retirement-rules.js","lib/retirement-actions.js","lib/retirement-resources.js","lib/retirement-report.js","lib/retirement-service.js",
"lib/worktime-intake.js","lib/worktime-rules.js","lib/worktime-actions.js","lib/worktime-resources.js","lib/worktime-report.js","lib/worktime-service.js",
"lib/annual-leave-intake.js","lib/annual-leave-rules.js","lib/annual-leave-actions.js","lib/annual-leave-resources.js","lib/annual-leave-report.js","lib/annual-leave-service.js"];
const failures=[],warnings=[];
const [major,minor]=process.versions.node.split(".").map(Number);if(major<22||(major===22&&minor<13))failures.push(`Node 22.13+ required; current ${process.versions.node}`);
for(const file of requiredFiles)if(!fs.existsSync(path.join(root,file)))failures.push(`missing required file: ${file}`);
const packageJson=JSON.parse(fs.readFileSync(path.join(root,"package.json"),"utf8"));if(!String(packageJson.scripts?.build||"").includes("write-build-info.mjs"))failures.push("build script must emit Render build-info metadata");
function checkLegal(file,articles,label){const text=fs.readFileSync(path.join(root,file),"utf8");for(const article of articles)if(!text.includes(article))failures.push(`${label} legal source missing: ${article}`);if(!text.includes("law.go.kr"))failures.push(`${label} National Law Information Center source is missing`);return text;}
const wageLegal=fs.readFileSync(path.join(root,"lib/legal-rules.js"),"utf8");if(!wageLegal.includes("minimumwage.go.kr"))failures.push("minimum wage official source is missing");if(!wageLegal.includes("law.go.kr"))failures.push("National Law Information Center wage source is missing");
const dismissalLegal=checkLegal("lib/dismissal-rules.js",["제23조","제26조","제27조","제28조"],"dismissal");if(!dismissalLegal.includes("nlrc.go.kr"))failures.push("dismissal labor-board source is missing");
const retirementLegal=checkLegal("lib/retirement-rules.js",["제4조","제8조","제9조","제15조","제20조"],"retirement");if(!retirementLegal.includes("moel.go.kr"))failures.push("retirement MOEL calculator source is missing");
const worktimeLegal=checkLegal("lib/worktime-rules.js",["제50조","제53조","제54조","제55조","제56조"],"working-time");if(!worktimeLegal.includes("별표 1"))failures.push("working-time small-workplace scope source is missing");
const annualLegal=checkLegal("lib/annual-leave-rules.js",["제18조","제60조","제61조","제7조의2","2021다227100"],"annual-leave");for(const boundary of ["2026-08-20","2027-06-10"])if(!annualLegal.includes(boundary))failures.push(`annual-leave legal version boundary missing: ${boundary}`);
function checkClient(file,label){const text=fs.readFileSync(path.join(root,file),"utf8");if(!text.includes("sessionStorage"))failures.push(`${label} workspace must use sessionStorage for case access`);if(text.includes("localStorage"))failures.push(`${label} workspace must not persist the case token in localStorage`);if(!text.includes('querySelector("pre").textContent'))failures.push(`${label} document preview must use plain text rendering`);}
const wageWorkspace=fs.readFileSync(path.join(root,"wage-workspace.js"),"utf8");if(!wageWorkspace.includes("sessionStorage"))failures.push("wage workspace must use sessionStorage for case access");if(wageWorkspace.includes("localStorage"))failures.push("wage workspace must not persist the case token in localStorage");if(!wageWorkspace.includes("textContent = result.document"))failures.push("wage document preview must use plain text rendering");
checkClient("dismissal-intake-client.js","dismissal");checkClient("retirement-intake-client.js","retirement");checkClient("worktime-intake-client.js","working-time");checkClient("annual-leave-intake-client.js","annual-leave");
const browserE2E=fs.readFileSync(path.join(root,"scripts/browser-e2e.mjs"),"utf8");if(!browserE2E.includes("chromium.launch"))failures.push("browser E2E must launch Chromium");if(!/viewport\s*:\s*\{\s*width\s*:\s*390\s*,\s*height\s*:\s*844\s*\}/.test(browserE2E))failures.push("browser E2E must include a mobile viewport");for(const route of ["/dismissal-intake","/retirement-intake","/worktime-intake"])if(!browserE2E.includes(route))failures.push(`browser E2E must exercise ${route}`);if(!browserE2E.includes("사건 요약 복사"))failures.push("browser E2E must exercise Case Report export");
const annualBrowser=fs.readFileSync(path.join(root,"scripts/annual-leave-browser-e2e.mjs"),"utf8");if(!annualBrowser.includes("chromium.launch")||!annualBrowser.includes("/annual-leave-intake"))failures.push("annual leave browser E2E must exercise the Case flow");if(!/width\s*:\s*390\s*,\s*height\s*:\s*844/.test(annualBrowser))failures.push("annual leave browser E2E must include mobile viewport");
const productionSmoke=fs.readFileSync(path.join(root,"scripts/production-smoke.mjs"),"utf8");if(!productionSmoke.includes("EXPECTED_COMMIT"))failures.push("production smoke must verify the deployed commit");for(const route of ["/api/cases/wage-intake","/api/cases/dismissal-intake","/api/cases/retirement-intake","/api/cases/worktime-intake"])if(!productionSmoke.includes(route))failures.push(`production smoke must exercise ${route}`);if(!productionSmoke.includes('method: "DELETE"'))failures.push("production smoke must clean up its synthetic Cases");
const annualProduction=fs.readFileSync(path.join(root,"scripts/annual-leave-production-smoke.mjs"),"utf8");if(!annualProduction.includes("EXPECTED_COMMIT")||!annualProduction.includes("/api/cases/annual-leave-intake")||!annualProduction.includes('method:"DELETE"'))failures.push("annual leave production smoke must verify commit, Case API and cleanup");
const ci=fs.readFileSync(path.join(root,".github/workflows/ci.yml"),"utf8");if(!ci.includes("annual-leave-browser-e2e.mjs")||!ci.includes("annual-leave-production-smoke.mjs"))failures.push("CI must run annual leave E2E and production smoke");
const renderPath=path.join(root,"render.yaml");if(fs.existsSync(renderPath)){const text=fs.readFileSync(renderPath,"utf8");if(/plan:\s*free/.test(text)&&!/\n\s*disk:\s*\n/.test(text))warnings.push("Render free plan has no active persistent disk; Case data can be lost on redeploy/restart.");}
if(process.env.NODE_ENV==="production"&&process.env.REQUIRE_PERSISTENT_DB==="1"&&!process.env.DB_PATH)failures.push("REQUIRE_PERSISTENT_DB=1 but DB_PATH is not configured");
for(const warning of warnings)console.warn(`⚠ ${warning}`);if(failures.length){for(const failure of failures)console.error(`✖ ${failure}`);process.exit(1);}console.log(`✅ release gate passed (${requiredFiles.length} required files)`);
